# Generated by Django 3.0.2 on 2020-01-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='owner',
            field=models.CharField(default='temp', max_length=30),
            preserve_default=False,
        ),
    ]
